name: Microservice CI/CD Pipeline

on:
    push:
        branches:
            - main
            - feature/**
    pull_request:
        branches:
            - main

permissions:
    packages: write

jobs:
    microservice:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '17'
            - name: Build with Gradle
              run: ./gradlew build

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set should deploy
              id: should_deploy
              run: |
                echo "should_deploy=${{ github.ref_name == 'main' }}" >> $GITHUB_OUTPUT
                echo ":rocket: using branch ** ${{ github.ref_name }} ** should deploy: ${{ github.ref_name == 'main' }}" >> $GITHUB_STEP_SUMMARY

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: ${{ steps.should_deploy.outputs.should_deploy == 'true' }}
                tags: ghcr.io/b4rz99/cicd-project/devops-20251-0.0.1-snapshot:latest


