name: Microservice CI/CD Pipeline

on:
    push:
        branches:
            - main
            - feature/**
    pull_request:
        branches:
            - main

permissions:
    packages: write

jobs:
    microservice:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '17'
            - name: Build with Gradle
              run: ./gradlew build
            - name: Create container
              run: docker build -t ghcr.io/b4rz99/cicd-project/devops-20251-0.0.1-snapshot:latest .

            - name: Docker login
              env:
                CR_PAT: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Push container
              run: docker push ghcr.io/b4rz99/cicd-project/devops-20251-0.0.1-snapshot:latest



